name: Scripted maintenance

on: [ push, pull_request_target ]

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: ${{ runner.temp }}/llvm
        key: llvm-14

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "14"
        directory: ${{ runner.temp }}/llvm
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: Run clang-format
      run: find -type f \( -name *.h -o -name *.cpp \) | xargs clang-format -style=file -i

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: maintenance
